title: "HNRobert Online"
tagline: "HNRobert Online"
description: "HNRobert Online"
github_username: HNRobert
baseurl: "/HNRobert.github.io"
url: "https://HNRobert.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small